const URL='https://oibibghbgcdjyimkvere.supabase.co';
const KEY='sb_publishable_a2pl_IOhqK3c7_gHUBnnmw_MoKaoptI';
let token=localStorage.getItem('af_token'),user=null,profile=null;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(table,{method='GET',query='',body}={}){const r=await fetch(`${URL}/rest/v1/${table}${query}`,{method,headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=representation'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error((await r.json()).message||'Operazione non riuscita');return r.status===204?null:r.json()}
async function login(){try{const r=await fetch(`${URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});const x=await r.json();if(!r.ok)throw Error('Email o password non corrette');token=x.access_token;user=x.user;localStorage.setItem('af_token',token);await start()}catch(e){$('loginError').textContent=e.message}}
async function start(){if(!token)return;try{const r=await fetch(`${URL}/auth/v1/user`,{headers:{apikey:KEY,Authorization:`Bearer ${token}`}});if(!r.ok)throw Error();user=await r.json();profile=(await api('utenti',{query:`?id=eq.${user.id}&select=*`}))[0];if(!profile?.attivo)throw Error();$('login').classList.add('hidden');$('app').classList.remove('hidden');$('logout').classList.remove('hidden');$('welcome').textContent=`Buongiorno, ${(profile.nome_cognome||'').split(' ')[0]}`}catch{logout()}}
function logout(){localStorage.removeItem('af_token');token=null;location.reload()}
function geo(){return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({gps_latitudine:p.coords.latitude,gps_longitudine:p.coords.longitude,gps_precisione_metri:p.coords.accuracy}),()=>reject(Error('Attiva la posizione GPS e riprova.')),{enableHighAccuracy:true,timeout:15000}))}
function openPage(title,html){$('menu').classList.add('hidden');const p=$('page');p.innerHTML=`<div class="page-title"><button class="back">←</button><h2>${title}</h2></div>${html}`;p.classList.remove('hidden');p.querySelector('.back').onclick=menu}
function menu(){$('page').classList.add('hidden');$('menu').classList.remove('hidden')}
async function attendance(){openPage('Presenze','<div class="spinner">Caricamento…</div>');const rows=await api('timbrature',{query:`?dipendente_id=eq.${user.id}&select=tipo,registrata_at,luogo&order=registrata_at.desc&limit=10`});$('page').innerHTML+=`<div class="actions"><button id="in">REGISTRA ENTRATA</button><button id="out" class="secondary">REGISTRA USCITA</button></div><div id="msg"></div>${rows.map(x=>`<div class="item"><b>${x.tipo.toUpperCase()}</b><small>${new Date(x.registrata_at).toLocaleString('it-IT')} ${esc(x.luogo||'')}</small></div>`).join('')}`;$('page').querySelector('.spinner').remove();for(const [id,tipo] of [['in','entrata'],['out','uscita']])$(id).onclick=async()=>{try{$('msg').textContent='Rilevamento posizione…';const g=await geo();await api('timbrature',{method:'POST',body:{dipendente_id:user.id,tipo,registrata_at:new Date().toISOString(),...g}});$('msg').innerHTML='<p class="success">Presenza registrata.</p>';setTimeout(attendance,700)}catch(e){$('msg').innerHTML=`<p class="error">${esc(e.message)}</p>`}}}
async function documents(){openPage('I miei documenti','<div class="spinner">Caricamento…</div>');const rows=await api('dipendente_documenti',{query:`?dipendente_id=eq.${user.id}&attivo=eq.true&visibile_dipendente=eq.true&select=*&order=data_scadenza.asc`});render(rows.length?rows.map(x=>`<div class="item"><b>${esc(x.titolo)}</b><span class="badge">${esc(x.categoria)}</span><small>Scadenza: ${x.data_scadenza?new Date(x.data_scadenza).toLocaleDateString('it-IT'):'Nessuna'}</small>${x.documento_url?`<a href="${esc(x.documento_url)}" target="_blank">Apri documento</a>`:''}</div>`).join(''):'<p>Nessun documento disponibile.</p>')}
async function communications(){openPage('Comunicazioni','<div class="spinner">Caricamento…</div>');const rows=await api('comunicazione_destinatari',{query:`?dipendente_id=eq.${user.id}&select=comunicazione_id,letta_at,confermata_at,comunicazioni(*)&order=comunicazione_id.desc`});render(rows.map(x=>{const c=x.comunicazioni;return `<div class="item"><b>${esc(c.titolo)}</b><span class="badge">${esc(c.priorita)}</span><p>${esc(c.messaggio)}</p>${!x.confermata_at&&c.richiede_conferma?`<button onclick="confirmMessage('${c.id}')">LETTO E CONFERMATO</button>`:''}</div>`}).join('')||'<p>Nessuna comunicazione.</p>')}
async function confirmMessage(id){await api('comunicazione_destinatari',{method:'PATCH',query:`?dipendente_id=eq.${user.id}&comunicazione_id=eq.${id}`,body:{letta_at:new Date().toISOString(),confermata_at:new Date().toISOString()}});communications()}
async function company(){openPage('Informazioni azienda','<div class="spinner">Caricamento…</div>');const x=(await api('configurazione_azienda',{query:'?select=*&limit=1'}))[0]||{};render(`<h3>${esc(x.ragione_sociale||'Arte In Ferro Lascari')}</h3><p>${esc([x.indirizzo,x.comune,x.provincia].filter(Boolean).join(' · '))}</p><p>${esc(x.telefono_principale||'')}<br>${esc(x.email||'')}<br>${esc(x.pec||'')}</p>`)}
async function contacts(){openPage('Contatti utili','<div class="spinner">Caricamento…</div>');const rows=await api('contatti_azienda',{query:'?attivo=eq.true&select=*&order=ordine.asc'});render(rows.map(x=>`<div class="item"><b>${esc(x.nome)}</b><small>${esc(x.ruolo_reparto||x.tipo)}</small>${x.telefono?`<a href="tel:${esc(x.telefono)}">${esc(x.telefono)}</a>`:''}</div>`).join('')||'<p>Nessun contatto disponibile.</p>')}
async function vehicleOptions(){const v=await api('mezzi',{query:'?attivo=eq.true&select=id,targa,descrizione&order=descrizione'});return v.map(x=>`<option value="${x.id}">${esc(x.targa)} · ${esc(x.descrizione)}</option>`).join('')}
async function fuel(){openPage('Carburante mezzo','<div class="spinner">Caricamento…</div>');render(`<label>Mezzo<select id="vehicle"><option value="">Seleziona…</option>${await vehicleOptions()}</select></label><label>Chilometri<input id="km" type="number"></label><label>Litri<input id="liters" type="number" step=".01"></label><label>Importo €<input id="amount" type="number" step=".01"></label><label>Distributore<input id="station"></label><button id="save">SALVA RIFORNIMENTO</button><div id="msg"></div>`);$('save').onclick=async()=>submitWithGeo('rifornimenti',{dipendente_id:user.id,mezzo_id:$('vehicle').value,km:+$('km').value,litri:+$('liters').value,importo:$('amount').value?+$('amount').value:null,distributore:$('station').value,data_ora:new Date().toISOString()})}
async function anomaly(){openPage('Segnala anomalia',`<label>Tipo<select id="type"><option value="sicurezza">Sicurezza</option><option value="mezzo">Mezzo</option><option value="attrezzatura">Attrezzatura</option><option value="cantiere">Cantiere</option><option value="altro">Altro</option></select></label><label>Titolo<input id="title"></label><label>Descrizione<textarea id="description"></textarea></label><button id="save">INVIA SEGNALAZIONE</button><div id="msg"></div>`);$('save').onclick=()=>submitWithGeo('anomalie',{segnalata_da:user.id,tipo:$('type').value,titolo:$('title').value,descrizione:$('description').value})}
async function submitWithGeo(table,body){try{$('msg').textContent='Rilevamento posizione…';const g=await geo();await api(table,{method:'POST',body:{...body,...g}});$('msg').innerHTML='<p class="success">Salvato correttamente.</p>'}catch(e){$('msg').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function reports(){openPage('I miei rapportini','<div class="spinner">Caricamento…</div>');const rows=await api('rapportini',{query:`?dipendente_id=eq.${user.id}&select=id,luogo,data_ora_inizio,ore_totali,stato,clienti(ragione_sociale)&order=data_ora_inizio.desc`});render(`<button id="newReport">+ NUOVO RAPPORTINO</button>${rows.map(x=>`<div class="item"><b>${esc(x.clienti?.ragione_sociale||'Cliente')}</b><small>${new Date(x.data_ora_inizio).toLocaleString('it-IT')} · ${esc(x.luogo)} · ${esc(x.ore_totali||0)} h</small><span class="badge">${esc(x.stato)}</span></div>`).join('')||'<p>Nessun rapportino.</p>'}`);$('newReport').onclick=openReportForm}
async function openReportForm(){openPage('Nuovo rapportino','<div class="spinner">Caricamento…</div>');const [clients,vehicles,employees]=await Promise.all([api('clienti',{query:'?select=id,ragione_sociale&order=ragione_sociale'}),api('mezzi',{query:'?attivo=eq.true&select=id,targa,descrizione&order=descrizione'}),api('v_collaboratori_attivi',{query:'?select=id,nome_cognome&order=nome_cognome'})]);const now=new Date(),later=new Date(now.getTime()+3600000),local=d=>new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);render(`<div class="actions"><button id="newClient" class="secondary">+ NUOVO CLIENTE</button></div><label>Cliente *<select id="rClient">${clients.map(x=>`<option value="${x.id}">${esc(x.ragione_sociale)}</option>`).join('')}</select></label><label>Luogo / cantiere *<input id="rPlace"></label><label>Tipo intervento<select id="rType"><option value="montaggio_posa">Montaggio / posa</option><option value="manutenzione_riparazione">Manutenzione / riparazione</option><option value="sopralluogo">Sopralluogo</option><option value="consegna_ritiro">Consegna / ritiro</option><option value="lavorazione_officina">Lavorazione in officina</option><option value="altro">Altro</option></select></label><label>Inizio<input id="rStart" type="datetime-local" value="${local(now)}"></label><label>Fine<input id="rEnd" type="datetime-local" value="${local(later)}"></label><label>Mezzo<select id="rVehicle"><option value="">Nessuno</option>${vehicles.map(x=>`<option value="${x.id}">${esc(x.targa)} · ${esc(x.descrizione)}</option>`).join('')}</select></label><label>Km mezzo<input id="rKm" type="number"></label><label>Descrizione attività *<textarea id="rDescription"></textarea></label><h3>Collaboratori presenti</h3><div class="checklist">${employees.filter(x=>x.id!==user.id).map(x=>`<label><input type="checkbox" name="team" value="${x.id}">${esc(x.nome_cognome)}</label>`).join('')||'<p>Nessun collaboratore disponibile.</p>'}</div><h3>Foto cantiere</h3><input id="rPhotos" type="file" accept="image/*" capture="environment" multiple><h3>Firma cliente *</h3><canvas id="signature" class="signature"></canvas><button id="clearSign" class="secondary">CANCELLA FIRMA</button><br><button id="saveReport">SALVA E INVIA</button><div id="msg"></div>`);setupSignature();$('newClient').onclick=createClient;$('saveReport').onclick=()=>saveWebReport(vehicles)}
async function createClient(){const name=prompt('Ragione sociale del nuovo cliente:')?.trim(),address=name&&prompt('Indirizzo del cliente:')?.trim();if(!name||!address)return;try{const rows=await api('clienti',{method:'POST',body:{ragione_sociale:name,indirizzo:address}}),x=rows[0],o=document.createElement('option');o.value=x.id;o.textContent=x.ragione_sociale;$('rClient').append(o);$('rClient').value=x.id}catch(e){$('msg').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
let signatureChanged=false;function setupSignature(){const c=$('signature'),ctx=c.getContext('2d'),scale=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*scale;c.height=r.height*scale;ctx.scale(scale,scale);ctx.lineWidth=2.5;ctx.lineCap='round';let down=false,last;const pos=e=>{const q=c.getBoundingClientRect();return{x:e.clientX-q.left,y:e.clientY-q.top}};c.onpointerdown=e=>{down=true;last=pos(e);c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!down)return;const p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;signatureChanged=true};c.onpointerup=()=>down=false;$('clearSign').onclick=()=>{ctx.clearRect(0,0,c.width,c.height);signatureChanged=false}}
async function upload(bucket,path,data,type){const r=await fetch(`${URL}/storage/v1/object/${bucket}/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':type,'x-upsert':'true'},body:data});if(!r.ok)throw Error((await r.json()).message||'Caricamento allegato non riuscito')}
async function compressPhoto(file){const bitmap=await createImageBitmap(file),ratio=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=Math.round(bitmap.width*ratio);c.height=Math.round(bitmap.height*ratio);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();return new Promise(ok=>c.toBlob(ok,'image/jpeg',.78))}
async function saveWebReport(vehicles){try{const place=$('rPlace').value.trim(),description=$('rDescription').value.trim(),start=new Date($('rStart').value),end=new Date($('rEnd').value);if(place.length<2||description.length<2||!end.getTime()||end<=start||!signatureChanged)throw Error('Completa luogo, orari, descrizione e firma.');$('msg').textContent='Rilevamento posizione e salvataggio…';const g=await geo(),id=crypto.randomUUID(),vehicleId=$('rVehicle').value||null,vehicle=vehicles.find(x=>x.id===vehicleId);await api('rapportini',{method:'POST',body:{id,dipendente_id:user.id,cliente_id:$('rClient').value,luogo:place,mezzo_id:vehicleId,targa_mezzo:vehicle?.targa||null,km_mezzo:$('rKm').value?+$('rKm').value:null,tipologia_intervento:$('rType').value,data_ora_inizio:start.toISOString(),data_ora_fine:end.toISOString(),descrizione,stato:'bozza',...g,gps_rilevato_at:new Date().toISOString()}});const team=[...document.querySelectorAll('[name=team]:checked')].map(x=>({rapportino_id:id,dipendente_id:x.value}));if(team.length)await api('rapportino_collaboratori',{method:'POST',body:team});const sign=await new Promise(ok=>$('signature').toBlob(ok,'image/png')),signPath=`${user.id}/${id}/firma_cliente.png`;await upload('rapportini-firme',signPath,sign,'image/png');for(const file of $('rPhotos').files){const photoId=crypto.randomUUID(),path=`${user.id}/${id}/${photoId}.jpg`,compressed=await compressPhoto(file);await upload('rapportini-foto',path,compressed,'image/jpeg');await api('rapportino_foto',{method:'POST',body:{id:photoId,rapportino_id:id,foto_url:path}})}await api('rapportini',{method:'PATCH',query:`?id=eq.${id}`,body:{firma_cliente_url:signPath,stato:'inviato'}});$('msg').innerHTML='<p class="success">Rapportino inviato correttamente.</p>';setTimeout(reports,900)}catch(e){$('msg').innerHTML=`<p class="error">${esc(e.message)}</p>`}}
function render(html){const p=$('page'),head=p.querySelector('.page-title').outerHTML;p.innerHTML=head+html;p.querySelector('.back').onclick=menu}
$('loginButton').onclick=login;$('logout').onclick=logout;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>({attendance,reports,fuel,anomaly,documents,communications,company,contacts}[b.dataset.page]()).catch(e=>render(`<p class="error">${esc(e.message)}</p>`)));if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');start();
